### PR TITLE
Catch panics during packet reassembly.

### PR DESCRIPTION
**Pull request by mgritter**
This covers the known bug... but, it's not clear whether the
reassembly layer can successfully recover afterwards, or if additional
cleanup is needed.

### CODE REVIEW

**Comment by mgritter** [comment]
One open question here is whether to re-panic if the error is not of a known type, such as an out-of-bound slice.

**Comment by mgritter** [comment]
Example panic:
```
[ERROR] Panic during packet handling: Oh noes, UDP!
goroutine 100 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/akitasoftware/akita-cli/pcap.(*NetworkTrafficParser).packetToParsedNetworkTraffic.func1()
	/home/mark/akita-cli/pcap/net_parse.go:199 +0x3d
panic({0x12c7c60, 0x19a2be0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/akitasoftware/akita-cli/pcap.(*NetworkTrafficParser).packetToParsedNetworkTraffic(0xc001ccc000, 0xc0022ea2c0?, 0x762110b7?, {0x19b49e8, 0xc0022ea2c0})
	/home/mark/akita-cli/pcap/net_parse.go:241 +0x411
github.com/akitasoftware/akita-cli/pcap.(*NetworkTrafficParser).ParseFromInterface.func1()
	/home/mark/akita-cli/pcap/net_parse.go:155 +0x1ff
created by github.com/akitasoftware/akita-cli/pcap.(*NetworkTrafficParser).ParseFromInterface
	/home/mark/akita-cli/pcap/net_parse.go:129 +0x34f
```

**Comment by liujed** [comment]
> Example panic:
> 
> ```
> [ERROR] Panic during packet handling: Oh noes, UDP!
> ... 8< ...
> ```

Does it actually say this? 😂

**Comment by mgritter** [comment]
> Does it actually say this? 😂

No, I tested by adding a panic on the UDP switch.

**Comment by mgritter** [comment]
PR to test this in staging: https://github.com/akitasoftware/infra/pull/1224

**Review by thatplguy — APPROVED** [review]

**Pull request merged**
